version: 2

updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    reviewers:
      - INRIX-Yuguo-Li
    ignore:
      - dependency-name: 'eslint'
        versions: ['^8.x']